### ISSUE TITLE
[Bug]: Cannot build wheel v19.24.4

### ISSUE THREAD

**Issue by FedericoCozziVM** [davisking/dlib#2943]
### What Operating System(s) are you seeing this problem on?

Linux (x86-64)

### dlib version

19.24.4

### Python version

3.10.12

### Compiler

Cmake 3.29.0

### Expected Behavior

It should install dlib at its latest version with pip installing syntax:
```bash
pip install --upgrade dlib
```

### Current Behavior

```terminal
pip install dlib

Collecting dlib
  Using cached dlib-19.24.4.tar.gz (3.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: dlib
  Building wheel for dlib (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for dlib (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      running bdist_wheel
      running build
      running build_ext
      Traceback (most recent call last):
        File "/home/user/Desktop/venv/bin/cmake", line 5, in <module>
          from cmake import cmake
      ModuleNotFoundError: No module named 'cmake'
      
      ERROR: CMake must be installed to build dlib
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for dlib
Failed to build dlib
```

### Steps to Reproduce

```bash
pip install --upgrade pip
pip install ---upgrade wheel cmake
pip install dlib
```

### Anything else?

(cmake is installed correctly and it successfully install dlib==19.24.2)

**Comment by davisking** [comment]
cmake isn't really installed right. Try `apt install cmake`.  For whatever reason the version of cmake that comes from pip is broken on a lot of systems.

**Comment by FedericoCozziVM** [comment]
@davisking Unfortunately I already tried that :( Running `sudo apt install cmake` gives me `cmake is already the newest version (3.22.1-1ubuntu1.22.04.2)`

**Comment by arrufat** [comment]
Are you sure you're using the system-wide CMake instead of the one installed by pip?

**Comment by FedericoCozziVM** [comment]
@arrufat you're right, I was using pip's one I guess, as you can see from the error traceback it takes it from virtualenv... however, I tried to uninstall it and the error is the same, this time taking the system-wide cmake (in  `/.local`):
```
Collecting dlib
  Using cached dlib-19.24.4.tar.gz (3.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: dlib
  Building wheel for dlib (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for dlib (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      running bdist_wheel
      running build
      running build_ext
      Traceback (most recent call last):
        File "/home/user/.local/bin/cmake", line 5, in <module>
          from cmake import cmake
      ModuleNotFoundError: No module named 'cmake'
      
      ERROR: CMake must be installed to build dlib
      
      [end of output]
```

I checked, and the version installed in venv (via pip) was 3.29.0.1 and the system-wide is 3.25.2. Do you know how to force some cmake version during `pip install` command?

Also, I tried to re-install dlib==19.24.2 forcing it the build (`pip install --no-cache-dir`) and it ran correctly

**Comment by arrufat** [comment]
`pip uninstall cmake` should do it

**Comment by FedericoCozziVM** [comment]
@arrufat that's what I tried, in fact the command in error comes from `/home/user/.local/bin/cmake` ...  but still no success

**Comment by arrufat** [comment]
I would try the following things
- remove all cmake installations (until `which cmake` returns nothing)
- build dlib in a new and clean virtualenv (`python -m venv venv && source venv/bin/activate && pip install cmake==3.25 && pip install dlib`)

**Comment by Goktug** [comment]
I am experiencing the same issue as well.

**Comment by Goktug** [comment]
> I still haven't solved it in my env, but I must say that it's probably a cmake installation issue as @arrufat and @davisking suggested. In fact, I tried to install everything from scratch in an Ubuntu docker image and version 19.24.4 is build and installed just fine

Hmm, are you using the latest cmake version?

**Comment by escalate007** [comment]
> I am experiencing the same issue as well. `dlib==19.24.2` is working fine but I am having an issue with the latest release.
> 
> P.S. Trying it in dockerized env.

I tried again and again about 19.24.4 but failed, then follow your advice, replace it with 19.24.2 .It's working now.

**Comment by Yuanyuan-888** [comment]
I am using linux system, and now the cmake version is okay (>3.8)

However, I can not "pip install dlib"

It showed the following error "          cmd_obj.run()
        File "/tmp/pip-build-env-_31gghmv/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/tmp/pip-build-env-_31gghmv/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-_31gghmv/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 967, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-_31gghmv/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 130, in run
        File "<string>", line 170, in build_extension
        File "/opt/insy/miniconda/3.9/lib/python3.9/subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j64']' returned non-zero exit status 2.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for dlib
Failed to build dlib
ERROR: Could not build wheels for dlib, which is required to install pyproject.toml-based projects"

I think the same with this bug --cannot build wheels for dlib.

**Comment by AlanFRL** [comment]
- I had the same problems installing the face-recognition library and got it working after trying these versions of cmake and dlib:

pip install cmake==3.25.2
pip install dlib==19.24.2

- I'm using a virtual environment with Python 3.9.1 and Windows 11, Also in python global I do not have cmake or dlib installed, only in my virtual environment

**Comment by Yuanyuan-888** [comment]
> * I had the same problems installing the face-recognition library and got it working after trying these versions of cmake and dlib:
> 
> pip install cmake==3.25.2 pip install dlib==19.24.2
> 
> * I'm using a virtual environment with Python 3.9.1 and Windows 11, Also in python global I do not have cmake or dlib installed, only in my virtual environment

I am using linux system:
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.9.2009 (Core)
Release:        7.9.2009
Codename:       Core
This method did not work for me, still "ERROR: Failed building wheel for dlib
Failed to build dlib
ERROR: Could not build wheels for dlib, which is required to install pyproject.toml-based projects"

**Comment by davisking** [comment]
Try getting cmake from cmake.org and installing it with their official installer.  The versions of cmake available in pip are often broken.  I would really only use the official cmake.

**Comment by LTPPPP** [comment]
Collecting dlib
  Using cached dlib-19.24.4.tar.gz (3.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: dlib
  Building wheel for dlib (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for dlib (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      <string>:210: SyntaxWarning: invalid escape sequence '\('
      <string>:211: SyntaxWarning: invalid escape sequence '\('
      <string>:212: SyntaxWarning: invalid escape sequence '\('
      running bdist_wheel
      running build
      running build_ext

      ERROR: CMake must be installed to build dlib

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for dlib
Failed to build dlib
ERROR: Could not build wheels for dlib, which is required to install pyproject.toml-based projects

help me, i have this problem when downloading dlib

**Comment by jeltiy** [comment]
This worked for me (CentOS 8)

`yum install python3-devel`
`yum groupinstall 'Development Tools'`
`pip install dlib`

**Comment by LTPPPP** [comment]
but i use win 11

**Comment by davisking** [comment]
Cmake isn't installed correctly. You should get cmake from cmake.org. That will work. There are lot of other places that repackage it into semi-broken cmake installers. You probably have one of those.

**Comment by slothPete7773** [comment]
> * I had the same problems installing the face-recognition library and got it working after trying these versions of cmake and dlib:
> 
> pip install cmake==3.25.2 pip install dlib==19.24.2
> 
> * I'm using a virtual environment with Python 3.9.1 and Windows 11, Also in python global I do not have cmake or dlib installed, only in my virtual environment

This worked out for me while developing for Python in Docker container.

**Comment by nmww** [comment]
**win11**

`pip install cmake==3.25.2

pip install dlib==19.24.2`

  **(CentOS 8)**

`yum install python3-devel

yum groupinstall 'Development Tools'

pip install dlib`

**Comment by ben13300** [comment]
Dear ALL,
SAme issued.
UBUNTU : Ubuntu 24.04 LTS (Noble)
CMAKE installed with APT : cmake version 3.28.3
PIP INSTALL DLIB (19.24.2 or 19.24.4) : ERROR: Could not build wheels for dlib, which is required to install pyproject.toml-based projects
 Could you please help me ? 
Thanks

**Comment by ben13300** [comment]
> Dear ALL, SAme issued. UBUNTU : Ubuntu 24.04 LTS (Noble) CMAKE installed with APT : cmake version 3.28.3 PIP INSTALL DLIB (19.24.2 or 19.24.4) : ERROR: Could not build wheels for dlib, which is required to install pyproject.toml-based projects Could you please help me ? Thanks

SOLVED WITH DOCKER.

**Comment by DuySota** [comment]
> * I had the same problems installing the face-recognition library and got it working after trying these versions of cmake and dlib:
> 
> pip install cmake==3.25.2 pip install dlib==19.24.2
> 
> * I'm using a virtual environment with Python 3.9.1 and Windows 11, Also in python global I do not have cmake or dlib installed, only in my virtual environment

I have this error when installing
pip install cmake==3.25.2 && pip install dlib==19.24.2
Collecting cmake==3.25.2
  Using cached cmake-3.25.2-py2.py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.8 kB)
Using cached cmake-3.25.2-py2.py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (23.7 MB)
Installing collected packages: cmake
Successfully installed cmake-3.25.2
Collecting dlib==19.24.2
  Using cached dlib-19.24.2.tar.gz (11.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      Traceback (most recent call last):
        File "/home/sotatek/miniconda3/envs/elegan/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/sotatek/miniconda3/envs/elegan/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/sotatek/miniconda3/envs/elegan/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-jg7xvqok/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/tmp/pip-build-env-jg7xvqok/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-jg7xvqok/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 190, in <module>
      ModuleNotFoundError: No module named 'setuptools.command.test'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by MohamedLahmeri01** [comment]
still the same here even after installing it cmake from official website

**Comment by erudaperu** [comment]
Hey guys, I tried all the solutions above but it's still giving the same error.  I can't figure out what's causing the problem (running Fedora 42 KDE).  Any help/advice is appreciated at this point...

**Comment by mnbvcxz7654321** [comment]
https://github.com/davisking/dlib/issues/2943

**Comment by mnbvcxz7654321** [comment]
_user61711414292577_

**Comment by mnbvcxz7654321** [comment]
user61711414292577

![Image](https://github.com/user-attachments/assets/ae83a61f-7994-4512-af35-ba9338291c47)
